
YXB:逃跑防封菜单 --
 --YXB逃跑防异常
 --YXB逃跑防封号
gg.setRanges(gg.REGION_CODE_APP")
gg.searchNumber("262144;16384;1024, gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber(", gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(99999")
gg.editAll("0, gg.TYPE_DWORD")
gg.toast("防异常开启成功)
--gg.toast('防异常开启成功')
gg.setRanges(gg.REGION_C_DATA")
gg.searchNumber("32768;4096, gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber(", gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(99999")
gg.editAll("0, gg.TYPE_DWORD")
gg.toast("防封号开启成功)
--gg.toast('防封号开启成功')
YXB:逃生稳定菜单 --
 --稳定透视「大厅开」
 --疾跑无限「大厅开」
 --加速开锁「游戏开」
 --范围开门「游戏开」
 --疾跑加速「游戏开」
 --皮卡加速「游戏开」
 --护盾加血「大厅开」
gg.setRanges(gg.REGION_CODE_APP")
gg.searchNumber("0.30000001192;128.00001525879, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("0.30000001192, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("-1, gg.TYPE_FLOAT")
gg.toast("逃生用，追捕别用)
--gg.toast('逃生用，追捕别用')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("1000D;4.3;13D::, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("4.3, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("999, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("1;1.5;2;2.5::13, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("1, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("2.5, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("256D;8;0.20000000298;1.29999995232;1::, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("1.29999995232, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("5, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("6;0.20000000298;0;0;0;0::21, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("0.20000000298, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("0.4, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("1003D;1;0.01;13D::, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("1, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("1.7, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_CODE_APP")
gg.searchNumber("0.30000001192;8.0078804e-38, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("0.30000001192, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("9999999, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
YXB:逃生过人机菜单 --
 --秒开一切「大厅开」
 --秒开钥匙「游戏开」
 --人物神速「一局一开」
gg.setRanges(gg.REGION_CODE_APP")
gg.searchNumber("5.5, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber(", gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("99, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("1;1.5;2;2.5::13, gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("1, gg.TYPE_DWORD", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("99, gg.TYPE_DWORD")
gg.toast("开启成功)
--gg.toast('开启成功')
gg.setRanges(gg.REGION_ANONYMOUS")
gg.searchNumber("2.8;4.9, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.searchNumber("2.8, gg.TYPE_FLOAT", false", gg.SIGN_EQUAL", 0", -1")
gg.getResults(100")
gg.editAll("10, gg.TYPE_FLOAT")
gg.toast("开启成功)
--gg.toast('开启成功')
YXB:退出脚本 --
